/home/users/rikiya/miniconda3/envs/transformer-ssl/lib/python3.9/site-packages/torch/distributed/launch.py:163: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn(
The module torch.distributed.launch is deprecated and going to be removed in future.Migrate to torch.distributed.run
WARNING:torch.distributed.run:--use_env is deprecated and will be removed in future releases.
 Please read local_rank from `os.environ('LOCAL_RANK')` instead.
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : moby_main.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 2
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:12345
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchelastic_f4eenkmq/none_ompui813
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
/home/users/rikiya/miniconda3/envs/transformer-ssl/lib/python3.9/site-packages/torch/distributed/elastic/utils/store.py:52: FutureWarning: This is an experimental API and will be changed in future.
  warnings.warn(
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=127.0.0.1
  master_port=12345
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1]
  role_ranks=[0, 1]
  global_ranks=[0, 1]
  role_world_sizes=[2, 2]
  global_world_sizes=[2, 2]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_f4eenkmq/none_ompui813/attempt_0/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_f4eenkmq/none_ompui813/attempt_0/1/error.json
Traceback (most recent call last):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/moby_main.py", line 22, in <module>
Traceback (most recent call last):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/moby_main.py", line 22, in <module>
    from data import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/__init__.py", line 1, in <module>
    from data import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/__init__.py", line 1, in <module>
    from .build import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 242, in <module>
    from .build import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 242, in <module>
    class stain_norm(object):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 243, in stain_norm
    class stain_norm(object):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 243, in stain_norm
    def get_stain_normalizer(self, path=config.AUG.STAIN_NORM_REF_PATH, method='macenko'):
NameError: name 'config' is not defined
    def get_stain_normalizer(self, path=config.AUG.STAIN_NORM_REF_PATH, method='macenko'):
NameError: name 'config' is not defined
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 50756) of binary: /home/users/rikiya/miniconda3/envs/transformer-ssl/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=12345
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1]
  role_ranks=[0, 1]
  global_ranks=[0, 1]
  role_world_sizes=[2, 2]
  global_world_sizes=[2, 2]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_f4eenkmq/none_ompui813/attempt_1/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_f4eenkmq/none_ompui813/attempt_1/1/error.json
Traceback (most recent call last):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/moby_main.py", line 22, in <module>
Traceback (most recent call last):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/moby_main.py", line 22, in <module>
    from data import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/__init__.py", line 1, in <module>
    from data import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/__init__.py", line 1, in <module>
    from .build import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 242, in <module>
    from .build import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 242, in <module>
    class stain_norm(object):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 243, in stain_norm
    class stain_norm(object):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 243, in stain_norm
    def get_stain_normalizer(self, path=config.AUG.STAIN_NORM_REF_PATH, method='macenko'):
NameError: name 'config' is not defined
    def get_stain_normalizer(self, path=config.AUG.STAIN_NORM_REF_PATH, method='macenko'):
NameError: name 'config' is not defined
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 50836) of binary: /home/users/rikiya/miniconda3/envs/transformer-ssl/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 2/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=2
  master_addr=127.0.0.1
  master_port=12345
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1]
  role_ranks=[0, 1]
  global_ranks=[0, 1]
  role_world_sizes=[2, 2]
  global_world_sizes=[2, 2]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_f4eenkmq/none_ompui813/attempt_2/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_f4eenkmq/none_ompui813/attempt_2/1/error.json
Traceback (most recent call last):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/moby_main.py", line 22, in <module>
Traceback (most recent call last):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/moby_main.py", line 22, in <module>
    from data import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/__init__.py", line 1, in <module>
    from data import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/__init__.py", line 1, in <module>
    from .build import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 242, in <module>
    from .build import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 242, in <module>
    class stain_norm(object):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 243, in stain_norm
    class stain_norm(object):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 243, in stain_norm
    def get_stain_normalizer(self, path=config.AUG.STAIN_NORM_REF_PATH, method='macenko'):
NameError: name 'config' is not defined
    def get_stain_normalizer(self, path=config.AUG.STAIN_NORM_REF_PATH, method='macenko'):
NameError: name 'config' is not defined
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 50884) of binary: /home/users/rikiya/miniconda3/envs/transformer-ssl/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 1/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=3
  master_addr=127.0.0.1
  master_port=12345
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1]
  role_ranks=[0, 1]
  global_ranks=[0, 1]
  role_world_sizes=[2, 2]
  global_world_sizes=[2, 2]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_f4eenkmq/none_ompui813/attempt_3/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_f4eenkmq/none_ompui813/attempt_3/1/error.json
Traceback (most recent call last):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/moby_main.py", line 22, in <module>
Traceback (most recent call last):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/moby_main.py", line 22, in <module>
    from data import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/__init__.py", line 1, in <module>
    from data import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/__init__.py", line 1, in <module>
    from .build import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 242, in <module>
    from .build import build_loader
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 242, in <module>
    class stain_norm(object):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 243, in stain_norm
    class stain_norm(object):
  File "/home/users/rikiya/contrastive_strap/SSL-Transformer-Histopathology/Transformer-SSL/data/build.py", line 243, in stain_norm
    def get_stain_normalizer(self, path=config.AUG.STAIN_NORM_REF_PATH, method='macenko'):
NameError: name 'config' is not defined
    def get_stain_normalizer(self, path=config.AUG.STAIN_NORM_REF_PATH, method='macenko'):
NameError: name 'config' is not defined
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 50898) of binary: /home/users/rikiya/miniconda3/envs/transformer-ssl/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:Local worker group finished (FAILED). Waiting 300 seconds for other agents to finish
/home/users/rikiya/miniconda3/envs/transformer-ssl/lib/python3.9/site-packages/torch/distributed/elastic/utils/store.py:70: FutureWarning: This is an experimental API and will be changed in future.
  warnings.warn(
INFO:torch.distributed.elastic.agent.server.api:Done waiting for other agents. Elapsed: 0.00040459632873535156 seconds
{"name": "torchelastic.worker.status.FAILED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": 0, "group_rank": 0, "worker_id": "50898", "role": "default", "hostname": "sh02-16n08.int", "state": "FAILED", "total_run_time": 55, "rdzv_backend": "static", "raw_error": "{\"message\": \"<NONE>\"}", "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\", \"local_rank\": [0], \"role_rank\": [0], \"role_world_size\": [2]}", "agent_restarts": 3}}
{"name": "torchelastic.worker.status.FAILED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": 1, "group_rank": 0, "worker_id": "50899", "role": "default", "hostname": "sh02-16n08.int", "state": "FAILED", "total_run_time": 55, "rdzv_backend": "static", "raw_error": "{\"message\": \"<NONE>\"}", "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\", \"local_rank\": [1], \"role_rank\": [1], \"role_world_size\": [2]}", "agent_restarts": 3}}
{"name": "torchelastic.worker.status.SUCCEEDED", "source": "AGENT", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": null, "group_rank": 0, "worker_id": null, "role": "default", "hostname": "sh02-16n08.int", "state": "SUCCEEDED", "total_run_time": 55, "rdzv_backend": "static", "raw_error": null, "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\"}", "agent_restarts": 3}}
/home/users/rikiya/miniconda3/envs/transformer-ssl/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:354: UserWarning: 

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE                
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 50898 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/home/users/rikiya/miniconda3/envs/transformer-ssl/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/users/rikiya/miniconda3/envs/transformer-ssl/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/users/rikiya/miniconda3/envs/transformer-ssl/lib/python3.9/site-packages/torch/distributed/launch.py", line 173, in <module>
    main()
  File "/home/users/rikiya/miniconda3/envs/transformer-ssl/lib/python3.9/site-packages/torch/distributed/launch.py", line 169, in main
    run(args)
  File "/home/users/rikiya/miniconda3/envs/transformer-ssl/lib/python3.9/site-packages/torch/distributed/run.py", line 621, in run
    elastic_launch(
  File "/home/users/rikiya/miniconda3/envs/transformer-ssl/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/users/rikiya/miniconda3/envs/transformer-ssl/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/users/rikiya/miniconda3/envs/transformer-ssl/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
***************************************
          moby_main.py FAILED          
=======================================
Root Cause:
[0]:
  time: 2021-08-02_12:47:56
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 50898)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2021-08-02_12:47:56
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 50899)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************

